url: https://portofolio-jekyll-vn3s.vercel.app
baseurl: ""

# Site settings
title: Mikail BAYRAKTAR
email: mikail.bayraktar@epitch.eu
formspree_endpoint: "https://formspree.io/f/xgojeqnk"
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Kay Garland
  pic: 1
  position: Lead Designer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Larry Parker
  pic: 2
  position: Lead Marketer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Diana Petersen
  pic: 3
  position: Lead Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)


# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty

# Exclude files from production build
exclude:
  - node_modules
  - vendor
  - .bundle
  - _site
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - build.sh
  - mail
  - js/contact_me.js
  - .git
  - .gitignore
  - .jekyll-cache
  - .vercelignore
  - vercel.json
  - .ruby-version

# Include hidden files
include:
  - .htaccess

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# GitHub Pages compatibility
github:
  is_project_page: false
